---
name: PR comment trigger

"on":
  issue_comment:
    types: [created]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v3
  check-comment:
    name: PR Comment
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '/run-tests' &&
      github.event.comment.author_association == 'MEMBER'
    steps:
      - name: Check comment
        run: |
          echo "Comment check passed. Proceeding to next job."
  pr-checkpoint-status:
    name: "PR Checkpoint Status"
    runs-on: ubuntu-latest
    needs: [check-comment]
    steps:
      - run: |
          echo "PR Checkpoint Status. Noop"
